export const idCards = [
  {
    name: 'John',
    lastName: 'Doe',
    city: 'New York',
    address: '123 Main Street',
    expires: '31-12-2025',
    photo: 'https://i.dummyjson.com/data/products/3/thumbnail.jpg',
  },
  {
    name: 'Romin',
    lastName: 'Irani',
    city: 'New York',
    address: '123 Main Street',
    expires: '31-12-2025',
    photo: 'https://i.dummyjson.com/data/products/6/thumbnail.png',
  },
  {
    name: 'Jane',
    lastName: 'Smith',
    city: 'Los Angeles',
    address: '789 Pine Avenue',
    expires: '31-12-2024',
    photo: 'https://i.dummyjson.com/data/products/9/thumbnail.jpg',
  },
  {
    name: 'Alex',
    lastName: 'Johnson',
    city: 'Chicago',
    address: '101 Maple Drive',
    expires: '31-12-2025',
    photo: 'https://i.dummyjson.com/data/products/99/thumbnail.jpg',
  },
  {
    name: 'Emily',
    lastName: 'Brown',
    city: 'San Francisco',
    address: '202 Cedar Lane',
    expires: '31-12-2023',
    photo: 'https://i.dummyjson.com/data/products/98/thumbnail.jpg',
  },
  {
    name: 'Michael',
    lastName: 'Williams',
    city: 'Houston',
    address: '303 Elm Court',
    expires: '31-12-2024',
    photo: 'https://i.dummyjson.com/data/products/92/thumbnail.jpg',
  },
  {
    name: 'Olivia',
    lastName: 'Davis',
    city: 'Miami',
    address: '404 Birch Road',
    expires: '31-12-2025',
    photo: 'https://i.dummyjson.com/data/products/84/thumbnail.jpg',
  },
];
